name: ğŸš€ Deploy website on push

on:
  push:
    branches: ["main"]
    paths:
      - web/**

jobs:
  web-deploy:
    name: ğŸ‰ FTP Deploy
    runs-on: ubuntu-latest
    steps:
      - name: ğŸšš Get latest code
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v3.0.0
        with:
          version: latest
      - name: ğŸ— Create css and js File
        uses: actions/setup-node@v3.8.1
        with:
          node-version: 18
          cache: "pnpm"
      - name: Install Depedency
        run: cd web && pnpm i
      - name: Build Assets
        run: cd web && pnpm build
      - name: ğŸ“‚ Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          local-dir: web/
          server: ${{ secrets.KA_FTP_HOST }}
          username: ${{ secrets.KA_FTP_USERNAME }}
          password: ${{ secrets.KA_FTP_PASSWORD }}
          server-dir: kanggara/budgetin/
      - name: ğŸ“¦ Composer install
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SOP_HOST }}
          username: ${{ secrets.SOP_SSH_USERNAME }}
          password: ${{ secrets.SOP_SSH_PASSWORD }}
          port: ${{ secrets.SOP_SSH_PORT }}
          script: cd ~/kanggara/budgetin/ && ls -la && composer u && composer i
